# Generated by Django 5.2.9 on 2026-01-01 14:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="设备编号"
                    ),
                ),
                ("model", models.CharField(max_length=100, verbose_name="型号")),
                (
                    "manufacturer",
                    models.CharField(
                        default="未知厂商", max_length=100, verbose_name="生产厂商"
                    ),
                ),
                (
                    "purchase_date",
                    models.DateField(blank=True, null=True, verbose_name="购入时间"),
                ),
                (
                    "purpose",
                    models.CharField(
                        blank=True,
                        default="未知用途",
                        max_length=200,
                        null=True,
                        verbose_name="实验用途",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("available", "可用"), ("unavailable", "不可用")],
                        default="可用",
                        max_length=20,
                        verbose_name="可用状态",
                    ),
                ),
                (
                    "price_internal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="校内租用价格（元/2小时）",
                    ),
                ),
                (
                    "price_external",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="校外租用价格（元/2小时）",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "设备",
                "verbose_name_plural": "设备管理",
                "ordering": ["device_code"],
            },
        ),
    ]
