# Generated by Django 5.2.9 on 2026-01-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('available', '可用'), ('unavailable', '不可用')], default='available', max_length=20, verbose_name='可用状态'),
        ),
    ]
