# Generated by Django 5.2.9 on 2026-01-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('available', '正常'), ('maintenance', '维修中'), ('discarded', '已报废')], default='available', help_text='设备物理状态：正常/维修中/已报废。时段可用性由预约情况决定。', max_length=20, verbose_name='设备状态'),
        ),
    ]
