# Generated by Django 5.2.9 on 2026-01-01 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0001_initial"),
        ("user", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="预约编号"
                    ),
                ),
                ("booking_date", models.DateField(verbose_name="预约日期")),
                ("time_slot", models.CharField(max_length=20, verbose_name="预约时段")),
                (
                    "purpose",
                    models.TextField(blank=True, null=True, verbose_name="借用用途"),
                ),
                (
                    "teacher_id",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="指导教师编号",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待管理员审批"),
                            ("admin_approved", "管理员已批准（待负责人审批）"),
                            ("manager_approved", "全部审批通过"),
                            ("admin_rejected", "管理员已拒绝"),
                            ("manager_rejected", "负责人已拒绝"),
                            ("cancelled", "用户已撤销"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="审批状态",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.userinfo",
                        verbose_name="申请人",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="devices.device",
                        verbose_name="预约设备",
                    ),
                ),
            ],
            options={
                "verbose_name": "预约申请",
                "verbose_name_plural": "预约申请",
            },
        ),
        migrations.CreateModel(
            name="ApprovalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval_level",
                    models.CharField(
                        choices=[("admin", "管理员"), ("manager", "负责人")],
                        max_length=20,
                        verbose_name="审批级别",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("approve", "批准"), ("reject", "拒绝")],
                        max_length=10,
                        verbose_name="审批操作",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="审批备注"),
                ),
                (
                    "approval_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="审批时间"),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审批人",
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booking.booking",
                        verbose_name="关联预约",
                    ),
                ),
            ],
            options={
                "verbose_name": "审批记录",
                "verbose_name_plural": "审批记录",
            },
        ),
    ]
