# Generated by Django 5.2.10 on 2026-01-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrecord',
            name='approval_level',
            field=models.CharField(choices=[('teacher', '指导教师'), ('admin', '管理员'), ('manager', '负责人')], max_length=20, verbose_name='审批级别'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('teacher_pending', '待指导教师审批'), ('pending', '待管理员审批'), ('admin_approved', '管理员已批准（待负责人审批）'), ('manager_approved', '全部审批通过'), ('admin_rejected', '管理员已拒绝'), ('teacher_rejected', '指导教师已拒绝'), ('manager_rejected', '负责人已拒绝'), ('cancelled', '用户已撤销')], default='pending', max_length=20, verbose_name='审批状态'),
        ),
    ]
