# Generated by Django 5.2.9 on 2026-01-15 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_approvalrecord_approval_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('teacher_pending', '待指导教师审批'), ('pending', '待管理员审批'), ('admin_approved', '管理员已批准（待负责人审批）'), ('manager_approved', '全部审批通过'), ('admin_rejected', '管理员已拒绝'), ('teacher_rejected', '指导教师已拒绝'), ('manager_rejected', '负责人已拒绝'), ('cancelled', '用户已撤销')], default='teacher_pending', max_length=20, verbose_name='审批状态'),
        ),
    ]
