# Generated by Django 5.2.9 on 2026-01-15 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_status'),
        ('user', '0003_remove_userinfo_advisor_userinfo_advisors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='finance_confirmed',
            field=models.BooleanField(default=False, verbose_name='财务处确认'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='缴费金额'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', '未缴费'), ('paid', '已缴费'), ('refunded', '已退款')], default='unpaid', max_length=20, verbose_name='缴费状态'),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='退款金额'),
        ),
        migrations.AddField(
            model_name='booking',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_bookings', to='user.userinfo', verbose_name='指导教师'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('teacher_pending', '待指导教师审批'), ('pending', '待管理员审批'), ('admin_approved', '管理员已批准（待负责人审批）'), ('manager_approved', '全部审批通过'), ('payment_pending', '待缴费'), ('teacher_rejected', '指导教师已拒绝'), ('admin_rejected', '管理员已拒绝'), ('manager_rejected', '负责人已拒绝'), ('cancelled', '用户已撤销')], default='pending', max_length=20, verbose_name='审批状态'),
        ),
    ]
