"""
Django settings for jnu_lab_system project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-=_jewn_^t+sz#zm9qs@yhf6*$y6ru^abr$0+9cqoe7#*t@*a1h"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

# Custom error handlers
# 当DEBUG=False时，这些处理器会显示自定义的错误页面
# 当DEBUG=True时，Django会显示详细的调试信息
HANDLER400 = 'jnu_lab_system.views.bad_request'
HANDLER403 = 'jnu_lab_system.views.permission_denied'
HANDLER404 = 'jnu_lab_system.views.page_not_found'
HANDLER500 = 'jnu_lab_system.views.server_error'


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    'lab_management',
    'devices',
    'user',
    'booking',
    'ledger',
    'manager',
    'labadmin',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "jnu_lab_system.multi_role_middleware.MultiRoleSessionMiddleware",  # 多角色会话支持（必须在AuthenticationMiddleware之后）
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "jnu_lab_system.middleware.StaffAccessControlMiddleware",  # 工作人员访问控制（已禁用，保留功能）
]

ROOT_URLCONF = "jnu_lab_system.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "jnu_lab_system.context_processors.user_info_context",  # 添加用户信息上下文处理器
            ],
            "debug": DEBUG,  # 开发环境启用模板调试
        },
    },
]

WSGI_APPLICATION = "jnu_lab_system.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# 开发环境禁用缓存，确保代码更新后立即生效
if DEBUG:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
        }
    }
    # CSRF配置：开发环境使用会话存储CSRF token，避免Cookie问题
    CSRF_USE_SESSIONS = True
    CSRF_COOKIE_HTTPONLY = False  # 允许JavaScript访问（如果需要）
    
    # 会话配置：确保每个用户有独立的session，防止会话混淆
    SESSION_COOKIE_HTTPONLY = True  # 防止JavaScript访问session cookie（安全）
    SESSION_COOKIE_SAMESITE = 'Lax'  # 防止CSRF攻击
    SESSION_SAVE_EVERY_REQUEST = False  # 不每次都保存session（性能优化）
    SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # 浏览器关闭后session不立即过期
    SESSION_COOKIE_AGE = 86400  # session过期时间：24小时（秒）
    SESSION_COOKIE_NAME = 'sessionid'  # 明确指定session cookie名称
    SESSION_COOKIE_SECURE = False  # 开发环境不需要HTTPS
    SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # 使用数据库存储session，确保每个用户独立

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
