"""
Django settings for jnu_lab_system project.

Generated by 'django-admin startproject' using Django 5.2.9.
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-=_jewn_^t+sz#zm9qs@yhf6*$y6ru^abr$0+9cqoe7#*t@*a1h"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 合并：保留了本地开发常用的主机地址
ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

# 合并：保留了他人增加的自定义错误处理器
# 当 DEBUG=False 时生效，对应 jnu_lab_system/views.py 中的处理函数
HANDLER400 = 'jnu_lab_system.views.bad_request'
HANDLER403 = 'jnu_lab_system.views.permission_denied'
HANDLER404 = 'jnu_lab_system.views.page_not_found'
HANDLER500 = 'jnu_lab_system.views.server_error'


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # 业务功能模块
    'lab_management',
    'devices',       # 设备管理
    'user',          # 人员/用户管理
    'booking',       # 你编写的预约/审核系统
    'ledger',        # 他人增加的台账系统 (已保留)
    'manager',
    'labadmin',      # 实验室管理界面
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "jnu_lab_system.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "jnu_lab_system.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# 建议：如果面向国内用户，可以考虑将 LANGUAGE_CODE 改为 'zh-hans'，TIME_ZONE 改为 'Asia/Shanghai'
LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')] # 确保静态文件夹被正确识别

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"