# Generated by Django 5.2.9 on 2026-01-01 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_code",
                    models.CharField(
                        help_text="学生填学号，教师填工号，校外人员填自定义编号（如O开头）",
                        max_length=20,
                        unique=True,
                        verbose_name="用户编号/学号/工号",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="姓名")),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("student", "校内学生"),
                            ("teacher", "校内教师"),
                            ("external", "校外人员"),
                        ],
                        max_length=10,
                        verbose_name="用户类型",
                    ),
                ),
                (
                    "department",
                    models.CharField(max_length=100, verbose_name="所在学院/单位"),
                ),
                ("phone", models.CharField(max_length=11, verbose_name="联系电话")),
                (
                    "gender",
                    models.CharField(
                        choices=[("男", "男"), ("女", "女")],
                        default="男",
                        max_length=2,
                        verbose_name="性别",
                    ),
                ),
                (
                    "major",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="专业"
                    ),
                ),
                (
                    "advisor",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="指导教师"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="职称"
                    ),
                ),
                (
                    "research_field",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="研究方向"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="职务"
                    ),
                ),
                (
                    "company_address",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="单位地址"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="借用资格（正常/禁用）"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "auth_user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关联登录账号",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户信息",
                "verbose_name_plural": "用户信息",
                "ordering": ["-create_time"],
            },
        ),
    ]
