# Generated by Django 5.2.9 on 2026-01-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userinfo_approval_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='advisor',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='advisors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'teacher'}, related_name='students', to='user.userinfo', verbose_name='指导教师'),
        ),
    ]
